### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by Umesh-JNU** [cjrh/excitertools#35]
![image](https://user-images.githubusercontent.com/56982559/123147639-e9e40480-d47c-11eb-8b36-3a254bd09d30.png)
Why I'm getting this error, even by using the exact same example from the docs as you can see in the above image.

**Comment by cjrh** [comment]
Hi @Umesh-JNU 

Thank you for your report.

I notice that you're directly calling a function called `bucket()`.  This library, `excitertools` does not have such a free-standing function. I assume you're talking about *more-itertools.bucket()*, which is over here: https://github.com/more-itertools/more-itertools

Nevertheless, I looked into this, using both *more-itertools* and this library, *excitertools*.  In fact, *excitertools* simply wraps many of the functions in *more-itertools* so we would expect the same behaviour in both.

To try to reproduce your example, I did this:

## more-itertools

```python
>>> iterable = ['a1', 'b1', 'c1', 'a2', 'b2', 'c2', 'b3']
>>> key = lambda x: x[0]                                 
>>> s = more_itertools.bucket(iterable, key=key)         
>>> sorted(s)                                            
['a', 'b', 'c']                                          
>>> list(s['a'])                                         
['a1', 'a2']            
```

## excitertools
                       
```python                                 
>>> iterable = ['a1', 'b1', 'c1', 'a2', 'b2', 'c2', 'b3']
>>> b = Iter(iterable).bucket(key=lambda x: x[0])        
>>> sorted(b)                                            
['a', 'b', 'c']                                          
>>> list(b['a'])                                         
['a1', 'a2']                                             
```
Thus, I did not get the error in either case.

Looking more closely at your code, the line that complains is this:

```python
s = bucket(iterable, key=lambda x: x[0])
```

And the error message given is that `'str' object is not callable`. The only thing on that line appears to be the identifier `bucket`, which makes me think that somehow your identifier `bucket` has somehow been initialised as a string, and not the function from *more-itertools*.

If you could provide a [short, self-contained example](http://sscce.org/) of code that I can run, and produce the error, that will help.  Please do not link to a notebook.

**Comment by Umesh-JNU** [comment]
Thanks for your reply. I got it. My mistake.
Should I delete the issue?

**Comment by cjrh** [comment]
No worries, I can just close it here 👍🏼
